### ISSUE TITLE
Image flashing: not working

### ISSUE THREAD

**Issue by mugurumov** [Hacks4ROS/meta-h4r-ev3#4]
I have followed the instructions written [here](http://hacks4ros.github.io/h4r_ev3_ctrl/) but I'm not able to make it properly.

Have you think about providing a whole image instead of two partitions?

I have tried it out in MacOs and Ubuntu.
I have used `gunzip` command

I'm aware that this is not the best site to rise an issue of this type.
Thanks

**Comment by mugurumov** [comment]
Finally I have made it, this are the steps I have made (I don't like how I have made it)
- With `gparted` erase & create the partitions you mention.
- Unzip the `boot` partition
- Copy the kernel and the .scr file into the SD `fat16` partition.
- unzip the filesystem
- Copy the filesystem into `etx4` partition of SD card.

I haven't been able to do it with `gunzip` or `tar` commands, the partitions get corrupted

**Comment by cyborg-x1** [comment]
Yeah, I did not find it in the documentation of Yocto how to let it make this file. My colleague found it out in our companies project, but I did not have the time to work on EV3 again. I did this in 5 months always on the evenings in my free time and currently I have some other things to do in that time, sorry ... 

The partitions get corrupted? Did you unmount correctly? Well just for information, you should execute 

`sync`

after you copied the files to the SD Card. Linux does not write the files directly, they are still in cache, even if it tells you that it is finished. If you eject the card without  unmounting it properly, it will mostly result in corrupted files.

**Comment by mugurumov** [comment]
Ok thanks. If anyone gets this, I hope it is useful. 
I will try to play around with EV3. So I might rise you issues if I'm blocked. Hope you don't mind. If you think I can make some tutorials or so, just let me know.
